# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Register_Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 600)
        MainWindow.setStyleSheet("\n"
"background-color:rgb(209, 213, 213);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -10, 801, 101))
        self.frame.setStyleSheet("background-color:rgb(255, 17, 59)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 30, 571, 61))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.submit_btn = QtWidgets.QPushButton(self.frame)
        self.submit_btn.setGeometry(QtCore.QRect(640, 40, 141, 41))
        self.submit_btn.setStyleSheet("QPushButton{\n"
"background-color:rgb(63, 99, 139);\n"
"border:3px solid white;\n"
"border-radius:20px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"border:3px solid white;\n"
"color:black;\n"
"}")
        self.submit_btn.setObjectName("submit_btn")
        self.submit_btn_2 = QtWidgets.QPushButton(self.frame)
        self.submit_btn_2.setGeometry(QtCore.QRect(480, 40, 141, 41))
        self.submit_btn_2.setStyleSheet("QPushButton{\n"
"border:3px solid white;\n"
"border-radius:20px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"border:3px solid white;\n"
"color:black;\n"
"}")
        self.submit_btn_2.setObjectName("submit_btn_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(30, 100, 751, 251))
        self.frame_2.setStyleSheet("background-color:white;\n"
"border-radius:20;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:black;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(50, 90, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:black;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(50, 140, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:black;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(50, 190, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:black;")
        self.label_5.setObjectName("label_5")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(300, 270, 781, 281))
        self.frame_3.setStyleSheet("background-color:white;\n"
"border-radius:20;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(50, 40, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:black;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(50, 90, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:black;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(50, 140, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:black;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(50, 190, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:black;")
        self.label_9.setObjectName("label_9")
        self.name_entry = QtWidgets.QLineEdit(self.frame_2)
        self.name_entry.setGeometry(QtCore.QRect(190, 30, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.name_entry.setFont(font)
        self.name_entry.setStyleSheet("QLineEdit{\n"
"background-color:white;\n"
"border: 2px solid rgb(209, 213, 213);\n"
"border-radius: 20px;\n"
"color:red;\n"
"}\n"
"QLineEdit:focus{\n"
"border:2px solid red;\n"
"}")
        self.name_entry.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.name_entry.setInputMask("")
        self.name_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.name_entry.setObjectName("name_entry")
        self.contact_entry = QtWidgets.QLineEdit(self.frame_2)
        self.contact_entry.setGeometry(QtCore.QRect(190, 80, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.contact_entry.setFont(font)
        self.contact_entry.setMouseTracking(False)
        self.contact_entry.setStyleSheet("QLineEdit{\n"
"background-color:white;\n"
"border: 2px solid rgb(209, 213, 213);\n"
"border-radius: 20px;\n"
"color:red;\n"
"}\n"
"QLineEdit:focus{\n"
"border:2px solid red;\n"
"}")
        self.contact_entry.setMaxLength(11)
        self.contact_entry.setCursorPosition(0)
        self.contact_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.contact_entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.contact_entry.setObjectName("contact_entry")
        self.email_entry = QtWidgets.QLineEdit(self.frame_2)
        self.email_entry.setGeometry(QtCore.QRect(190, 130, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.email_entry.setFont(font)
        self.email_entry.setMouseTracking(False)
        self.email_entry.setStyleSheet("QLineEdit{\n"
"background-color:white;\n"
"border: 2px solid rgb(209, 213, 213);\n"
"border-radius: 20px;\n"
"color:red;\n"
"}\n"
"QLineEdit:focus{\n"
"border:2px solid red;\n"
"}")
        self.email_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.email_entry.setObjectName("email_entry")
        self.mail_entry = QtWidgets.QLineEdit(self.frame_2)
        self.mail_entry.setGeometry(QtCore.QRect(190, 190, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.mail_entry.setFont(font)
        self.mail_entry.setMouseTracking(False)
        self.mail_entry.setStyleSheet("QLineEdit{\n"
"background-color:white;\n"
"border: 2px solid rgb(209, 213, 213);\n"
"border-radius: 20px;\n"
"color:red;\n"
"}\n"
"QLineEdit:focus{\n"
"border:2px solid red;\n"
"}")
        self.mail_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.mail_entry.setObjectName("mail_entry")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(30, 360, 751, 201))
        self.frame_4.setStyleSheet("background-color:white;\n"
"border-radius:20;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(50, 20, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:black;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(50, 70, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:black;")
        self.label_11.setObjectName("label_11")
        self.user_entry = QtWidgets.QLineEdit(self.frame_4)
        self.user_entry.setGeometry(QtCore.QRect(180, 10, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.user_entry.setFont(font)
        self.user_entry.setMouseTracking(False)
        self.user_entry.setStyleSheet("QLineEdit{\n"
"background-color:white;\n"
"border: 2px solid rgb(209, 213, 213);\n"
"border-radius: 20px;\n"
"color:red;\n"
"}\n"
"QLineEdit:focus{\n"
"border:2px solid red;\n"
"}")
        self.user_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.user_entry.setObjectName("user_entry")
        self.password_entry = QtWidgets.QLineEdit(self.frame_4)
        self.password_entry.setGeometry(QtCore.QRect(180, 60, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.password_entry.setFont(font)
        self.password_entry.setMouseTracking(False)
        self.password_entry.setStyleSheet("QLineEdit{\n"
"background-color:white;\n"
"border: 2px solid rgb(209, 213, 213);\n"
"border-radius: 20px;\n"
"color:red;\n"
"}\n"
"QLineEdit:focus{\n"
"border:2px solid red;\n"
"}")
        self.password_entry.setText("")
        self.password_entry.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_entry.setCursorPosition(0)
        self.password_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.password_entry.setClearButtonEnabled(True)
        self.password_entry.setObjectName("password_entry")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(50, 120, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:black;")
        self.label_12.setObjectName("label_12")
        self.type_combo = QtWidgets.QComboBox(self.frame_4)
        self.type_combo.setGeometry(QtCore.QRect(180, 120, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.type_combo.setFont(font)
        self.type_combo.setStyleSheet("border: 3px solid rgb(199, 202, 202);\n"
"color: red;\n"
"background-color:white;\n"
"")
        self.type_combo.setEditable(False)
        self.type_combo.setCurrentText("")
        self.type_combo.setObjectName("type_combo")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(350, 130, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:black;")
        self.label_13.setObjectName("label_13")
        self.id_entry = QtWidgets.QLineEdit(self.frame_4)
        self.id_entry.setGeometry(QtCore.QRect(450, 120, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.id_entry.setFont(font)
        self.id_entry.setMouseTracking(False)
        self.id_entry.setStyleSheet("QLineEdit{\n"
"background-color:white;\n"
"border: 2px solid rgb(209, 213, 213);\n"
"border-radius: 20px;\n"
"color:red;\n"
"}\n"
"QLineEdit:focus{\n"
"border:2px solid red;\n"
"}")
        self.id_entry.setMaxLength(4)
        self.id_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.id_entry.setPlaceholderText("")
        self.id_entry.setObjectName("id_entry")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.type_combo.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "New Registration"))
        self.label.setText(_translate("MainWindow", "REGISTRATION"))
        self.submit_btn.setText(_translate("MainWindow", "LOGIN"))
        self.submit_btn_2.setText(_translate("MainWindow", "SUBMIT"))
        self.label_2.setText(_translate("MainWindow", "Full Name"))
        self.label_3.setText(_translate("MainWindow", "Contact #"))
        self.label_4.setText(_translate("MainWindow", "Email Address"))
        self.label_5.setText(_translate("MainWindow", "Mailing Address"))
        self.label_6.setText(_translate("MainWindow", "Full Name"))
        self.label_7.setText(_translate("MainWindow", "Contact #"))
        self.label_8.setText(_translate("MainWindow", "Email Address"))
        self.label_9.setText(_translate("MainWindow", "Mailing Address"))
        self.name_entry.setPlaceholderText(_translate("MainWindow", "Your Name Here"))
        self.contact_entry.setPlaceholderText(_translate("MainWindow", "Contact Number Here"))
        self.email_entry.setPlaceholderText(_translate("MainWindow", "abc@xyz.com"))
        self.mail_entry.setPlaceholderText(_translate("MainWindow", "Address"))
        self.label_10.setText(_translate("MainWindow", "Username"))
        self.label_11.setText(_translate("MainWindow", "Password"))
        self.user_entry.setPlaceholderText(_translate("MainWindow", "Username"))
        self.password_entry.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_12.setText(_translate("MainWindow", "Account Type"))
        self.type_combo.setPlaceholderText(_translate("MainWindow", "Select Type"))
        self.label_13.setText(_translate("MainWindow", "Member ID"))



