# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_window_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1001, 751)
        Form.setStyleSheet("background-color:rgb(49, 49, 49);\n"
"")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 20, 981, 101))
        self.frame.setStyleSheet("background-color:rgb(32, 32, 32);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.sub_search = QtWidgets.QComboBox(self.frame)
        self.sub_search.setGeometry(QtCore.QRect(120, 40, 271, 31))
        self.sub_search.setEditable(True)
        self.sub_search.setStyleSheet("QComboBox{\n"
"background-color:rgb(49, 49, 49);\n"
"color:white;\n"
"}")
        self.sub_search.setObjectName("sub_search")
        self.Diary_search = QtWidgets.QLineEdit(self.frame)
        self.Diary_search.setGeometry(QtCore.QRect(10, 40, 101, 31))
        self.Diary_search.setStyleSheet("background-color:rgb(49, 49, 49);\n"
"color:white;\n"
"")
        self.Diary_search.setObjectName("Diary_search")
        self.depart_search = QtWidgets.QComboBox(self.frame)
        self.depart_search.setGeometry(QtCore.QRect(400, 40, 191, 31))
        self.depart_search.setEditable(True)
        self.depart_search.setStyleSheet("QComboBox{\n"
"background-color:rgb(49, 49, 49);\n"
"color:white;\n"
"}")
        self.depart_search.setObjectName("depart_search")
        self.firm_search = QtWidgets.QComboBox(self.frame)
        self.firm_search.setGeometry(QtCore.QRect(600, 40, 191, 31))
        self.firm_search.setEditable(True)
        self.firm_search.setStyleSheet("QComboBox{\n"
"background-color:rgb(49, 49, 49);\n"
"color:white;\n"
"}")
        self.firm_search.setObjectName("firm_search")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 60, 16))
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(120, 20, 200, 16))
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(400, 20, 121, 16))
        self.label_3.setStyleSheet("color:white;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(600, 20, 111, 16))
        self.label_4.setStyleSheet("color:white;")
        self.label_4.setObjectName("label_4")
        self.search_btn = QtWidgets.QPushButton(self.frame)
        self.search_btn.setGeometry(QtCore.QRect(790, 40, 61, 32))
        self.search_btn.setStyleSheet("QPushButton{\n"
"image:url(:/New_images/search-12-16.png);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:red;\n"
"}")
        self.search_btn.setText("")
        self.search_btn.setFlat(True)
        self.search_btn.setObjectName("search_btn")
        self.new_add_btn = QtWidgets.QPushButton(self.frame)
        self.new_add_btn.setGeometry(QtCore.QRect(850, 40, 61, 31))
        self.new_add_btn.setStyleSheet("QPushButton{\n"
"image:url(:/New_images/add-file-16.png);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:red;\n"
"}")
        self.new_add_btn.setText("")
        self.new_add_btn.setFlat(True)
        self.new_add_btn.setObjectName("new_add_btn")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 139, 961, 751))
        self.scrollArea.setStyleSheet("background-color:rgb(32, 32, 32);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 959, 479))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalScrollBar = QtWidgets.QScrollBar(Form)
        self.verticalScrollBar.setGeometry(QtCore.QRect(970, 140, 16, 481))
        self.verticalScrollBar.setStyleSheet("QScrollBar:vertical{\n"
"background-color:rgb(32, 33, 36);\n"
"}\n"
"QScrollBar::handle:vertical {         \n"
"            min-height: 0px;\n"
"            border: 0px solid red;\n"
"            border-radius: 5px;\n"
"            background-color: rgb(92, 95, 141);\n"
"}\n"
"QScrollBar::add-line:vertical {       \n"
"            height: 0px;\n"
"            subcontrol-position: bottom;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::sub-line:vertical {\n"
"            height: 0 px;\n"
"            subcontrol-position: top;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"")
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Diary #"))
        self.label_2.setText(_translate("Form", "Subject"))
        self.label_3.setText(_translate("Form", "Department"))
        self.label_4.setText(_translate("Form", "Firm Name"))
